import turtle
x1=int(input("x좌표를 설정해주세요."))
y1=int(input("y좌표를 설정해주세요."))
x2=int(input('x좌표를 설정해주세요.'))
y2=int(input("y좌표를 설정해주세요."))
x3=int(input('x좌표를 설정해주세요.'))
y3=int(input("y좌표를 설정해주세요."))
t=turtle.Turtle()
t.shape('turtle')
t.goto(x1,y1)
t.goto(x2,y2)
t.goto(x3,y3)
turtle.done()