import turtle
t=turtle.Turtle()
turtle.shape("turtle")
stmp=t.stamp()
t.circle(-50,90)
t.shape("turtle")
stmp2=t.stamp()
t.circle(-50,90)
t.shape("turtle")
stmp3=t.stamp()
t.circle(-50,90)
t.shape("turtle")
stmp4=t.stamp()
t.circle(-50,90)
t.clearstamp(stmp2)
t.clearstamp(stmp4)
turtle.done()